### PR TITLE
Changing placement of lowered constant expressions

### LINKED ISSUE #50: Wrong encoding of complex constant initialization
In case of complex constant initialization of automatic variables, SPIRV contains global variable declaration with Storage Class: Function.
[ArrInit.txt](https://github.com/KhronosGroup/SPIRV-LLVM/files/117266/ArrInit.txt)

CL code example:
`kernel void test() { uint arr[] = { 123, 456 }; }`

Expected:

```
         ...
          %9 = OpVariable %8 UniformConstant %7
         %12 = OpFunction %10 None %11
         ...
               OpFunctionEnd
```

Actual:

```
         ...
          %9 = OpVariable %8 Function %7
         %12 = OpFunction %10 None %11
         ...
               OpFunctionEnd
```

### PR DESCRIPTION
**Pull request by AlexeySotkin**
According to SPIRV specification (p2.4):
"All OpVariable instructions in a function must be in the first block in the
function. These instructions, together with any immediately preceding OpLine
instructions, must be the first instructions in that block."
Therefore, changing insertion point of lowered constant expressions from
begining of the function to the point preceding the current instruction.
This partially fixes #50

### CODE REVIEW

**Comment by bader** [comment]
LGTM.

File: lib/SPIRV/SPIRVLowerConstExpr.cpp [hunk 1]
```diff
@@ -132,18 +132,18 @@ SPIRVLowerConstExpr::visit(Module *M) {
           if (auto CE = dyn_cast<ConstantExpr>(Op)) {
             SPIRVDBG(dbgs() << "[lowerConstantExpressions] " << *CE;)
             auto ReplInst = CE->getAsInstruction();
-            ReplInst->insertBefore(FBegin->begin());
```
Comment (yxsamliu) [inline lib/SPIRV/SPIRVLowerConstExpr.cpp:135]: Can we insert it at the end of the first BB? Then redundant instructions are easier to be merged by optimizations.

Comment (AlexeySotkin) [reply lib/SPIRV/SPIRVLowerConstExpr.cpp:135]: Fixed
